Revert "Merge branch 'master' of https://github.com/open-estuary/caliper"
This reverts commit c8965df13cc5d0156fc36e2a82030e7112feba59, reversing
changes made to 829b633ac72df0056dc37f460d37dcef0fe394da.

diff --git a/benchmarks/300.ltp/testcases/kernel/fs/acls/acl_test01 b/benchmarks/300.ltp/testcases/kernel/fs/acls/acl_test01
--- a/benchmarks/300.ltp/testcases/kernel/fs/acls/acl_test01
+++ b/benchmarks/300.ltp/testcases/kernel/fs/acls/acl_test01
@@ -41,8 +41,6 @@ export TCID=acltest01
 export TST_TOTAL=5
 export TST_COUNT=1
 
-. test.sh
-
 TMP=${TMP:=/tmp}
 
 TEST_USER1="acltest1"
@@ -54,33 +52,18 @@ FILE_ACL="$TMP/tacl/mount-ext3/test_file"
 FILE_ACL_LINK="$TMP/tacl/mount-ext3/test_file_link"
 TCbin=`pwd`
 
-COMMAND=$(command -v "getenforce" "setenforce" |wc -l)
-if [ $COMMAND -eq 2 ]; then
-	SELINUX=$(getenforce)
-else
-	SELINUX=""
-fi
-
 #-----------------------------------------------------------------------
 # FUNCTION:  do_setup
 #-----------------------------------------------------------------------
 
 do_setup(){
 
-	tst_require_root
-
 	rm -f $FILE_ACL
 	rm -f $FILE_ACL_LINK
 
-	# We couldn't consider whether the SElinux is Disable or Permissive.
-	# We only set it to Permissive when it it Enforcing.
-	if [ "$SELINUX" = "Enforcing" ]; then
-		echo "set the SElinux to Permissive."
-		setenforce 0
-	fi
-
 	if [ "x$TEST_USER1_HOMEDIR" = "x" ]; then
-		tst_brkm TBROK "Could not find user $TEST_USER1's home directory."
+		echo "Could not find user $TEST_USER1's home directory."
+		exit 1
 	fi
 
 	# XXX (garrcoop): why is cleanup junk being done in setup??? Bad test!!!
@@ -90,7 +73,8 @@ do_setup(){
 	useradd -d $TEST_USER1_HOMEDIR -m -g $TEST_USER1_GROUP $TEST_USER1 -s /bin/sh
 
 	if [ $? -ne 0 ]; then
-		tst_brkm TBROK "Could not add test user $TEST_USER1."
+		echo "Could not add test user $TEST_USER1."
+		exit 1
 	fi
 
 }
@@ -107,12 +91,6 @@ do_cleanup() {
 	mount | grep "$TMP/tacl/mount-ext3" && umount -d $TMP/tacl/mount-ext3
 	[ "x$LOOP_DEV" != x ] && losetup -d $LOOP_DEV
 	rm -rf $TMP/tacl
-
-	# We set it back to Enforcing.
-	if [ "$SELINUX" = "Enforcing" ]; then
-		echo "set the SElinux back to Enforcing."
-		setenforce 1
-	fi
 }
 
 #-----------------------------------------------------------------------
@@ -124,10 +102,14 @@ if [ "z$iam" = "z$TEST_USER1" ]
 then
 	echo ""
 else
-	tst_require_root
+	if [ $(id -ru) != 0 ]; then
+		tst_resm TCONF "must be root to execute this script"
+		exit 0
+	fi
 
 	if ! ( test -d $TMP/tacl || mkdir -m 777 $TMP/tacl) ; then
-		tst_brkm TBROK "Failed to create $TMP/tacl directory."
+		tst_resm TCONF "failed to create $TMP/tacl directory."
+		exit 1
 	fi
 
 	trap do_cleanup EXIT
@@ -137,18 +119,21 @@ else
 
 	dd if=/dev/zero of=$TMP/tacl/blkext3 bs=1k count=10240 && chmod 777 $TMP/tacl/blkext3
 	if [ $? -ne 0 ] ; then
-		tst_brkm TBROK "Failed to create $TMP/tacl/blkext3"
+		tst_resm TCONF "Failed to create $TMP/tacl/blkext3"
+		exit 0
 	fi
 
 	# Avoid hardcoded loopback device values (-f tries to find the first
 	# available loopback device name)!
 	if ! LOOP_DEV=$(losetup -f) || [ "x$LOOP_DEV" = x ]; then
-		tst_brkm TCONF "[ losetup.1 ] Failed to find an available loopback device -- is the required support compiled in your kernel?"
+		tst_resm TCONF "[ losetup.1 ] Failed to find an available loopback device -- is the required support compiled in your kernel?"
+		exit 0
 	fi
 
 	if ! losetup $LOOP_DEV $TMP/tacl/blkext3 2>&1 > /dev/null; then
 		echo ""
-		tst_brkm TCONF "[ losetup.2 ] Failed to setup the device."
+		tst_resm TCONF "[ losetup.2 ] Failed to setup the device."
+		exit 0
 	fi
 
 	mount | grep ext2
@@ -158,9 +143,11 @@ else
 		mount -t ext3 -o defaults,acl,user_xattr $LOOP_DEV $TMP/tacl/mount-ext3
 		if [ $? -ne 0 ]
 		then
+			echo ""
 			tst_resm TCONF "[ mount ] Make sure that ACL (Access Control List)"
-			tst_resm TCONF "\t and Extended Attribute are built into the kernel\n"
-			tst_brkm TCONF "\t Can not mount ext3 file system with acl and user_xattr options\n"
+			printf "\t and Extended Attribute are built into the kernel\n"
+			printf "\t Can not mount ext3 file system with acl and user_xattr options\n"
+			exit 1
 		fi
 	else
 
@@ -169,9 +156,11 @@ else
 		mount -t ext2 -o defaults,acl,user_xattr $LOOP_DEV $TMP/tacl/mount-ext3
 		if [ $? -ne 0 ]
 		then
+			echo ""
 			tst_resm TCONF "FAILED: [ mount ] Make sure that ACL (Access Control List)"
-			tst_resm TCONF "\t and Extended Attribute are built into the kernel\n"
-			tst_brkm TCONF "\t Can not mount ext2 file system with acl and user_xattr options\n"
+			printf "\t and Extended Attribute are built into the kernel\n"
+			printf "\t Can not mount ext2 file system with acl and user_xattr options\n"
+			exit 1
 		fi
 
 	fi
@@ -191,18 +180,20 @@ then
 	${TCbin}/acl_file_test $FILE_ACL
 	if [ $? -ne 0 ]
 	then
-		tst_resm TFAIL "Extended acls for files."
+		EXIT_CODE=1
+		echo "Extended acls for files (FAILED)"
 	else
-		tst_resm TPASS "Extended acls for files."
+		echo "Extended acls for files (PASSED)"
 	fi
 
 	echo "Trying extended acls for file links"
 	${TCbin}/acl_link_test $FILE_ACL_LINK
 	if [ $? -ne 0 ]
 	then
-		tst_resm TFAIL "Extended acls for links."
+		EXIT_CODE=1
+		echo "Extended acls for links (FAILED)"
 	else
-		tst_resm TPASS "Extended acls for links."
+		echo "Extended acls for links (PASSED)"
 	fi
 else
 	do_setup
@@ -220,18 +211,20 @@ else
 	${TCbin}/acl_file_test $FILE_ACL
 	if [ $? -ne 0 ]
 	then
-		tst_resm TFAIL "Extended acls for files."
+		EXIT_CODE=1
+		echo "Extended acls for files (FAILED)"
 	else
-		tst_resm TPASS "Extended acls for files."
+		echo "Extended acls for files (PASSED)"
 	fi
 
 	echo "Trying extended acls for file links"
 	${TCbin}/acl_link_test $FILE_ACL_LINK
 	if [ $? -ne 0 ]
 	then
-		tst_resm TFAIL "Extended acls for links."
+		EXIT_CODE=1
+		echo "Extended acls for links (FAILED)"
 	else
-		tst_resm TPASS "Extended acls for links."
+		echo "Extended acls for links (PASSED)"
 	fi
 
 	chown $TEST_USER1 $FILE_ACL
@@ -242,4 +235,4 @@ else
 	do_cleanup
 fi
 
-tst_exit
+exit $EXIT_CODE
